@extends('layouts.app')
@section('page-title', 'welcome')
@section ('content')
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
<h1>WELCOME MAIN</h1>
@endsection